start:
    	IN 10H
    	LXI B,03E8H     ;BC -> 1000dec (1ms*1000 = 1s)

count_up:
    	LDA 2000H		; DIAVAZW TA DIP-SWITCHES
    	ANI 0FH		; PETAW TA 4-MSB
	CPI 00H		; AN EINAI OLA SVISTA PERIMENE MEXRI NA ANAPSEI KAPOIO
	JZ count_up
    	MOV D,A    	; KAI APOTHIKEYW STO D
    	MVI A,FFH		; VAZW STO A TO FF ETSI WSTE +1 NA DINEI 0
cont_up:
    	MOV E,A		; APOTHIKEYW STO E THN CURRENT TIMH TOU METRITH
lock_up:
    	LDA 2000H     ; DIAVAZW KSANA TA DIP-SWITCHES 
    	ANI 80H		; KRATAW TO MSB
    	CPI 80H		; ELEGXW AN EINAI 1
    	JNZ lock_up	; AN DEN EINAI KSANA ELEGXW
    	MOV A,E		; ALLIWS VAZW STO A TIMH TOY METRITH
    	INR A		; AYKSANW THN TIMH TOY METRITH
    	CMA        
    	STA 3000H		; CMA LOGO ARNITIKIS LOGIKIS STOUS DIAKOPTES
    	CALL DELB
    	CMA
    	CMP D		; SIGKRINW ME TON ARITHMO POU DOTHIKE STA 4 LSB DIP SWITCHES
    	JZ count_down	; OTAN FTASEI STON ARITHMO KSEKINAEI ANTISTROFI METRISI
    	JMP cont_up

count_down:
    	MOV E,A
lock_down:
    	LDA 2000H		; CHECK FOR MSB
    	ANI 80H
    	CPI 80H
    	JNZ lock_down
    	MOV A,E
    	DCR A
    	CMA
    	STA 3000H
    	CMA
    	CPI 00H		; ELEGXO AN EFTASE STO 0
    	JZ count_up	; ALLAZW SE COUNT UP 	
	CALL DELB		; DEN KALEITAI KATHISTERISI GIA TO 0 GIATI GINETAI STO COUNT UP
    	JMP count_down	; ALLIWS SINEXISE TIN ANTISTROFI METRISI

END