IN 10H
LXI B,0A00H
START:
	CALL	KIND	; FERE APO TO PLIKTROLOGIO
	CPI 	05H	; AN A>0x5
	JNC	START	; PARE NEO NUM
   INR   A     ; X1+1
	MOV	C,A	; GRAPSE TON A STO B
FERE_Y:
	CALL	KIND	; FERE KAI TON EPOMENO	
	CPI	10H	; AN A>0x0F
	JNC	FERE_Y 
DONE:	
   STAX  B      ; VAZW TON A STH DIEYTHYNSH MNHMHS B-C (0A-(X1+1))
   LXI	D,0A00H	;FORTONO STO ZEVGOS D-E TIN THESI MNIMIS POU ARXIZOUN TA SEGMENTS
	CALL	STDM	 ;METAKINEI TO MINIMA POU KSEKINA STIN PARAPANW DIEUTHINSI STIN 
	CALL	DCD   ;DIEUTHINSI POU TO PERIPENEI I DCD, DCD PAROUSIAZEI STA SEGMENTS
	JMP	START 
END